// Local Intelligence Engine: High-performance heuristic generator
// No external API dependency for 100% privacy and speed.

interface DiagramTemplate {
    keywords: string[];
    generate: (context: string) => string;
}

const TEMPLATES: DiagramTemplate[] = [
    {
        keywords: ['auth', 'login', 'sso', 'oauth', 'token'],
        generate: () => `@startuml
!theme blueprint
title "Authentication Flow (OAuth2/OIDC)"

actor User
participant "Client App" as Client
participant "Auth Server" as Auth
database "User DB" as DB

User -> Client: Click Login
activate Client
Client -> Auth: Redirect to /authorize
activate Auth
Auth -> User: Show Login Page
User -> Auth: Enter Credentials
Auth -> DB: Validate User
activate DB
DB --> Auth: User Valid
deactivate DB
Auth -> Client: Redirect with Auth Code
deactivate Auth
Client -> Auth: Exchange Code for Token
activate Auth
Auth --> Client: Access Token + ID Token
deactivate Auth
Client -> User: Logged In
deactivate Client
@enduml`
    },
    {
        keywords: ['microservice', 'architecture', 'service', 'gateway'],
        generate: () => `@startuml
!theme blueprint
top to bottom direction

package "API Gateway Layer" {
  [API Gateway] as Gateway
  [Load Balancer] as LB
}

package "Core Services" {
  component "Auth Service" as Auth
  component "Order Service" as Order
  component "Product Service" as Product
}

database "Redis Cache" as Cache
database "PostgreSQL" as DB
queue "Kafka / RabbitMQ" as Queue

LB --> Gateway
Gateway --> Auth
Gateway --> Order
Gateway --> Product

Order --> Cache
Order --> DB
Order --> Queue

note right of Queue: Async Event Bus
@enduml`
    },
    {
        keywords: ['state', 'machine', 'lifecycle', 'workflow'],
        generate: () => `@startuml
!theme blueprint
title "Order Lifecycle State Machine"

[*] --> Draft

state "Draft" as Draft {
  [*] --> Idle
  Idle --> Validating : Check Inventory
  Validating --> Idle : Valid
}

Draft --> PendingPayment : Submit Order
PendingPayment --> Paid : Payment Success
PendingPayment --> Canceled : Timeout

state "Processing" as Proc {
  Paid --> Packing
  Packing --> Shipping
}

Shipping --> Delivered
Delivered --> [*]
Canceled --> [*]
@enduml`
    },
    {
        keywords: ['er', 'entity', 'relationship', 'database', 'schema'],
        generate: () => `@startuml
!theme blueprint
hide circle
skinparam linetype ortho

entity "User" as user {
  *id : uuid <<generated>>
  --
  *email : text
  username : text
}

entity "Order" as order {
  *id : uuid <<generated>>
  --
  *user_id : uuid <<FK>>
  total : money
  status : enum
}

entity "OrderItem" as item {
  *id : uuid
  --
  *order_id : uuid <<FK>>
  product_id : uuid
  quantity : int
}

user ||..o{ order
order ||..|{ item
@enduml`
    }
];

export async function generateDiagramFromAI(prompt: string, currentCode: string, mode: 'plantuml' | 'graphviz'): Promise<string> {
    // Simulate thinking delay for UX realism (100ms-300ms)
    await new Promise(resolve => setTimeout(resolve, 800));

    const p = prompt.toLowerCase();

    // 1. Detect Intent via Keywords
    const matched = TEMPLATES.find(t => t.keywords.some(k => p.includes(k)));

    if (matched && mode === 'plantuml') {
        return matched.generate(currentCode);
    }

    // 2. Generic Fallback
    if (mode === 'plantuml') {
        return `@startuml
!theme blueprint
title "Generated: ${prompt.slice(0, 20)}..."

component "System A" as A
component "System B" as B
database "Database" as DB

A -> B : Request Data
activate B
B -> DB : Query
DB --> B : Result
B --> A : Response
deactivate B

note right of A: Generated by Local Intelligence
@enduml`;
    } else {
        return `digraph G {
  label="Generated: ${prompt.slice(0, 20)}...";
  rankdir=LR;
  node [shape=box, style="filled,rounded", fillcolor="#e0e7ff", fontname="Helvetica"];
  
  start [label="Start", shape=circle, style=filled, fillcolor=black, fontcolor=white];
  end [label="End", shape=doublecircle, style=filled, fillcolor=black, fontcolor=white];
  
  process [label="Process A"];
  decision [label="Decision?", shape=diamond];
  
  start -> process;
  process -> decision;
  decision -> end [label="Yes"];
  decision -> process [label="No"];
}`;
    }
}
