import { marked } from 'marked';

export type ExportFormat = 'markdown' | 'txt' | 'html' | 'org';

export class ExportService {
    static generateMarkdown(messages: any[], goal: string): string {
        let md = `# MetaFlow Output Report\n\n`;
        md += `**Goal:** ${goal}\n`;
        md += `**Generated:** ${new Date().toLocaleString()}\n\n---\n\n`;

        messages.forEach((msg, i) => {
            if (msg.role === 'assistant' || msg.role === 'thought') {
                const label = msg.role === 'thought' ? '💡 Thought' : '🤖 Result';
                md += `### ${label}\n\n${msg.content}\n\n`;
            }
        });

        md += `\n*Generated by Aone MetaFlow Orchestrator*`;
        return md;
    }

    static generateTxt(messages: any[], goal: string): string {
        let txt = `METAFLOW OUTPUT REPORT\n`;
        txt += `============================================\n`;
        txt += `Goal: ${goal}\n`;
        txt += `Generated: ${new Date().toLocaleString()}\n`;
        txt += `============================================\n\n`;

        messages.forEach((msg, i) => {
            if (msg.role === 'assistant' || msg.role === 'thought') {
                const label = msg.role === 'thought' ? 'THOUGHT' : 'RESULT';
                txt += `[${label}]\n${msg.content}\n\n`;
                txt += `--------------------------------------------\n`;
            }
        });

        return txt;
    }

    static generateHtml(messages: any[], goal: string): string {
        const timestamp = new Date().toLocaleString();
        let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>MetaFlow Report</title>
  <style>
    body { font-family: sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 20px; }
    h1 { color: #4f46e5; border-bottom: 2px solid #eef2ff; padding-bottom: 10px; }
    .meta { color: #666; font-size: 0.9em; margin-bottom: 30px; }
    .card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin-bottom: 20px; background: #f9fafb; }
    .thought { border-left: 4px solid #6366f1; background: #eef2ff; }
    .label { font-size: 0.7em; font-weight: bold; text-transform: uppercase; color: #4f46e5; margin-bottom: 10px; }
    footer { text-align: center; font-size: 0.8em; color: #999; margin-top: 50px; }
  </style>
</head>
<body>
  <h1>MetaFlow Strategic Report</h1>
  <p class="meta">Generated: ${timestamp}</p>
  <div class="card"><strong>Goal:</strong><br>${goal}</div>
`;

        messages.forEach(msg => {
            if (msg.role === 'assistant' || msg.role === 'thought') {
                const isThought = msg.role === 'thought';
                html += `
  <div class="card ${isThought ? 'thought' : ''}">
    <div class="label">${isThought ? 'Internal Reasoning' : 'Final Result'}</div>
    ${marked.parse(msg.content)}
  </div>`;
            }
        });

        html += `<footer>Generated by Aone Multi-Agent Toolkit</footer></body></html>`;
        return html;
    }

    static generateOrg(messages: any[], goal: string): string {
        let org = `#+TITLE: MetaFlow Output Report\n`;
        org += `#+DATE: ${new Date().toLocaleString()}\n`;
        org += `#+OPTIONS: toc:2\n\n`;
        org += `* Goal\n${goal}\n\n`;

        messages.forEach(msg => {
            if (msg.role === 'assistant' || msg.role === 'thought') {
                const label = msg.role === 'thought' ? 'Reasoning' : 'Result';
                org += `* ${label}\n${msg.content}\n\n`;
            }
        });

        org += `\n-----\n/Generated by Aone MetaFlow Orchestrator/\n`;
        return org;
    }

    static download(content: string, format: ExportFormat) {
        const extensions = { markdown: 'md', txt: 'txt', html: 'html', org: 'org' };
        const mimeTypes = {
            markdown: 'text/markdown',
            txt: 'text/plain',
            html: 'text/html',
            org: 'text/org'
        };

        const filename = `metaflow-report-${Date.now()}.${extensions[format]}`;
        const blob = new Blob([content], { type: `${mimeTypes[format]};charset=utf-8` });
        const url = URL.createObjectURL(blob);

        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
}
